### ISSUE TITLE
"Attempting to include unknown block ..."

### ISSUE THREAD

**Issue by Happy-Ferret** [justinmeiners/srcweave#18]
Running the current master on any `.lit` file (including the Hello World example) yields the above output.

**Input**: ` srcweave --weave doc/ --formatter srcweave-format hello.lit`
**Output**:  `attempting to include unknown block "includes"`

### System: 

* OS: Windows 10/WSL1
* SBCL: 1.4.5.debian
* markdown: Discount

**Comment by justinmeiners** [comment]
Just tried with this exact command on the `hello.lit` and it worked correctly (debian).

I would guess it's related to Windows. I'll look into it. Thanks for the issue.

**Comment by justinmeiners** [comment]
https://bugs.launchpad.net/sbcl/+bug/720517

https://bugs.launchpad.net/sbcl/+bug/310185
