### ISSUE TITLE
UNIX file path support could be better

### ISSUE THREAD

**Issue by justinmeiners** [justinmeiners/srcweave#4]
folder names shouldn't need `/` attached to them, etc.

**Comment by atweiden** [comment]
Back when I was trying to riff on [Literate](https://github.com/zyedidia/Literate), I went with a leading `/` to differentiate file paths from code blocks, [e.g.](https://github.com/atweiden/finn/blob/master/doc/Syntax.md)

```markdown

--- /cities/WA.md
Washington
==========

---

In the above snippet, the contents of the Sectional Block `/cities/WA.md`
will be written to `$PROJECT_ROOT/cities/WA.md`.
```

I can see how it might be handled with a CLI argument or config file, though.

Just my 2c, but built-in syntax makes the prosé more self-contained, and it could also facilitate some degree of universal syntax highlighting to differentiate named code blocks from files.

(I haven’t perused much of your code, but it [looks like](https://github.com/justinmeiners/srcweave/blob/88c4b50330663ff5f97a700d5411b319f2375280/parse.lisp#L247) you’re currently differentiating files by requiring files have an extension.)

**Comment by justinmeiners** [comment]
This is great feedback. 

You are correct, I am using file extensions.

Your suggestion would solve an additional problem, which is manually specifying the code type of a block. Adding an extension to a block would help identify the type, without creating af ile.
